### ISSUE TITLE
TODO: 2023 Release

### ISSUE THREAD

**Issue by calum-chamberlain** [calum-chamberlain/GPHS445_notebooks#12]
- [x] #11 - channel naming to notebook 1
- [x] #10 -  reduce spectrogram length
- [x] Check all links
- [x] Check that fm plotting works with numpy release that removes `np.float` (hack this is needed)
- [x] Check all test pass
- [x] Check manually on Linux
- [x] Check manually on Windows
- [ ] Check manually on macOS
- [ ] Get Aleks to update the env in the lab
- [ ] Make clean 2023 branch and post archive to blackboard
